spring:
  sql:
    init:
      mode: always # /resources -> data.sql & schema.sql 실행 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/penta_ksy?createDatabaseIfNotExist=true # DB 없을 경우 자동 생성
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true # sql 가독성 있게 출력
        show_sql: true

jwt:
  secret:
    key: 6rmA7IOB7Jykand07Iuc7YGs66a/7YKkYmFzZTY07J247L2U65Sp7ZWp64uI64uk6riw7Iig6rO87KCc